### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.Cli#112]
Not sure what others think, but for me it is hard to imagine a world where I wouldn't want my project's CLI plugin as a global alias. There is already great documentation in the plugin example of configuring the global alias for your project. It even mentions the future possibility of installing plugin aliases.

There are various ways this could play out, but imho it would be great to be bundled in as part of the larger 'install' command of the CLI. When that 'install' command is run, it additionally will check your current directory to see if its a project (or it can find one of its parent directories is one) and suggest (or automatically setup) the plugin alias globally `npm install -g .`. 

If for whatever reason, rolling it into the main `install` command would prove difficult, we could simply have a separate `install-plugin` command.

**Comment by brandongregoryscott** [comment]
Makes sense to me 👍 I think we'd just need to look at the local `package.json` and determine if the bin name isn't `and-cli` to safely install the project globally.

**Comment by brandongregoryscott** [comment]
Published with [v1.5.0](https://github.com/AndcultureCode/AndcultureCode.Cli/releases/tag/v1.5.0) - let me know if it's all good 👍 I'll add an issue in the plugin example repo to update the documentation surrounding the global alias
