### ISSUE TITLE
Opt-in cloning of main AndcultureCode repos for workspace command

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.Cli#120]
It might be nice to force the user to opt-in to cloning all of the mainline AndcultureCode repos instead of doing it automatically once the base `workspace` command has been run. I didn't realize this was the default behavior, and ended up with a number of cloned repos in a directory that I didn't need them 😛 

We could do this a few ways, like prompting the user to confirm all of the clone actions before continuing when the `workspace` command is run without any flags, or a `-c, --clone` flag with a description about the behavior would work too

Didn't come to mind during the PR @wintondeshong, but what do you think?

**Comment by wintondeshong** [comment]
Yeah, that makes sense! Would be an easy change
