### ISSUE TITLE
webpack clean without restore causes error

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.Cli#133]
**Problem**
The webpack command presently ends with trying to start webpack (`react-scripts start`). If one only issues a clean `-c`, that causes an error `'react-scripts' is not recognized as an internal or external command` because `node_modules` is now gone and needs restored. 

**Solution**
If webpack command is issued with a clean, but not an accompanying restore, it should exit.

**Comment by brandongregoryscott** [comment]
Published with [v2.3.1](https://github.com/AndcultureCode/AndcultureCode.Cli/releases/tag/v2.3.1)
