### ISSUE TITLE
Investigate feasibility/benefit of porting project to Typescript

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.Cli#14]
**Description**
Investigate how much of a lift porting the project over to Typescript would be. Document any caveats or potential roadblocks, changes in development workflow, npm package publishing, etc.

**Comment by wintondeshong** [comment]
@brandongregoryscott should be entirely feasible. Believe we would ts-node to allow us to run it without an additional transpilation step. Probably better to start this sooner rather than later. Less to port :)

**Comment by wintondeshong** [comment]
Gonna hack on this some and see how it goes

**Comment by wintondeshong** [comment]
Initial findings:

- First pass port should be simple
- Getting to strict typings will take a bit more time
- While we can run "live" transpilation through ts-node (skipping need to keep .js artifacts), there is a noticeable delay running through `ts-node -T cli.ts`. So while we would use ts-node for development, we'd want to run a `tsc -p` when releasing new versions so there isn't any delay for end users

**Comment by wintondeshong** [comment]
After discussing internally with @Stefanie899 and @brandongregoryscott we are going in the direction of housing source files in `src` and adding an official build step to `lib` on releases. 

In an ideal world where transpiling typescript was trivial, we wouldn't need to output the javascript build and could just run "live" through ts-node. Development experience will be in that ideal, but publishing new versions will be output to 'lib' where end-users will use it.

**Comment by brandongregoryscott** [comment]
@wintondeshong I know you were hacking on this previously, I'd love to get us on typescript soon. Any thoughts on pushing up what you have and letting me wrap it up?

**Comment by wintondeshong** [comment]
Sorry for missing this @brandongregoryscott -- This has been sitting here long enough that I don't feel my branch helpful. We have a much better tuned approach for TS across our projects that starting this issue from scratch is probably easier. I'm going to unassign myself for now so others can take it on.

**Comment by brandongregoryscott** [comment]
No worries @wintondeshong! A lot has changed, for sure. I won't assign myself just yet, but I have been experimenting with an extended CLI and was able to get it on TS with minor hiccups over the weekend.

**Comment by brandongregoryscott** [comment]
Closing this as the initial port work has been completed and merged to [release/2.0.0](https://github.com/AndcultureCode/AndcultureCode.Cli/tree/release/2.0.0). Will report back when it has been merged down to `main`
