### ISSUE TITLE
Node 14 warnings "non existent property"

### ISSUE THREAD

**Issue by dylanjustice** [AndcultureCode/AndcultureCode.Cli#145]
Update shelljs to 0.8.4 to remove warning messages when using Node 14+
For reference https://github.com/nodejs/node/issues/32987

**Comment by brandongregoryscott** [comment]
Published with [v2.0.0-beta.3](https://github.com/AndcultureCode/AndcultureCode.Cli/releases/tag/v2.0.0-beta.3)
