### ISSUE TITLE
Entity Framework Core Add/Remove Migrations

### ISSUE THREAD

**Issue by dylanjustice** [AndcultureCode/AndcultureCode.Cli#15]
Create a command that allows you to add migrations, remove migrations and update the database given a project and a startup project for Entity Framework Core. 

i.e 
`and-cli --migrations -[add|remove] [MigrationName] -p [Project] -s [StartupProject]`

... or something

**Comment by brandongregoryscott** [comment]
I've already written this for the project cli I'm on, so it shouldn't be too much effort to port it over here. Thanks for the bringing up the issue @dylanjustice !

**Comment by wintondeshong** [comment]
@brandongregoryscott of course after I merged and published to npm (0.1.0), I realized we need to add documentation of the command to COMMANDS.md.

**Comment by brandongregoryscott** [comment]
> @brandongregoryscott of course after I merged and published to npm (0.1.0), I realized we need to add documentation of the command to COMMANDS.md.

Ah whoops, I totally forgot, too! I'll get a branch & PR out for this soon.

**Comment by wintondeshong** [comment]
Thanks @brandongregoryscott merged and closed 👍
