### ISSUE TITLE
Setup code coverage with istanbul 

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.Cli#16]
After configuration of jest, we need to go further and configure the code coverage

**Comment by rlynn523** [comment]
I'll take this if it's still available

**Comment by wintondeshong** [comment]
Go for it! Thank you 🙏

**Comment by rlynn523** [comment]
@wintondeshong istanbul is built into Jest, do you want me to get the test suite to successfully run and show coverage?

**Comment by rlynn523** [comment]
@wintondeshong what specifically are you looking to configure? Do you want to set thresholds?

**Comment by wintondeshong** [comment]
Yes, that’d be great!

**Comment by rlynn523** [comment]
Other than thresholds, what other configs do you want me to add?

**Comment by wintondeshong** [comment]
For now, thresholds will do. Thank you!
