### ISSUE TITLE
Update a nuget package throughout the solution.

### ISSUE THREAD

**Issue by dylanjustice** [AndcultureCode/AndcultureCode.Cli#24]
I want to be able to run a command that updates a nuget package that is referenced in multiple projects without having to navigate to each project and run `dotnet add package <packagename> -v <version>`

**Comment by brandongregoryscott** [comment]
I like this idea @dylanjustice . Do you have a vision for what the command would look like? Would it be an option under the `nuget` command, ie `and-cli nuget --upgrade AndcultureCode.CSharp.Core 1.0.0`?

Should there be some sort of prompt between each project that it finds to confirm the upgrade, or maybe just a little debugging output? ("Found AndcultureCode.CSharp.Core at version 0.9.6 in Project/Business/Core/Core.csproj, upgrading to 1.0.0")

**Comment by wintondeshong** [comment]
Merged and published with v0.5.0
