### ISSUE TITLE
Cli commands not responding in WSL

### ISSUE THREAD

**Issue by jebediahelliott** [AndcultureCode/AndcultureCode.Cli#40]
It seems that the commands are not getting read right when used in WSL. I'm using Ubuntu 18.04. When I type just `and-cli` the help menu is displayed but when I give it a command I get an error that the command does not exist. 
![image](https://user-images.githubusercontent.com/26680652/68975890-6ce1ab00-07c2-11ea-8ec5-1447641acf3b.png)
![image](https://user-images.githubusercontent.com/26680652/68975917-8551c580-07c2-11ea-9e5b-0a0a4f2fccaa.png)

**Comment by brandongregoryscott** [comment]
I had this same behavior, haven't figured out what the issue is. A workaround for me was cloning the repository and referencing the `and-cli-dev` alias instead.
