### ISSUE TITLE
Update webpack command to leverage node spawn

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.Cli#42]
**Problem**
ShellJS exec, no matter the setting, is leveraging node exec. The primary issue is that exec does not pipe output to the parent process correctly via streaming. Thus we have had to make work arounds to reformat the output.

**Solution**
Switch from using shelljs.exec to nodejs `spawn` (see webpack-test) for an example. This will allow for the identical experience to webpack dev server from formatting to overtaking the shell.

```javascript
const child = spawn(this.cmds.webpack, { stdio: "inherit", shell: true });
child.on("exit", (code, signal) => {
    if (code !== 0) {
        echo.error(`Exited with error ${signal}`);
        shell.exit(code);
    }

    dir.popd();
    echo.newLine();
    echo.message("Exited webpack");
});
```

**Comment by brandongregoryscott** [comment]
@wintondeshong I believe this was taken care of with my refactor in PR #55
