### ISSUE TITLE
dotnet-test - Add ability to run solution tests "by project"

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.Cli#52]
**Problem**
The `dotnet-test` command runs all of the test assemblies by the solution file itself. Normally, this should be fine, however - the underlying `dotnet test` runner fires off multiple assemblies to run at the same time, even if those assemblies are set to run tests within the suite in sequence. There's an issue where integration tests that are accessing the same database can and will collide, and the easiest workaround we have for this for the time being is to force the test assemblies to run in serial.

**Solution**

- Update the dotnest-test command to have a flag for running the solution "by project", which will look for any `*.Test*.csproj` files in the dotnet solution directory, and call `dotnet test` with those projects.

- Add a few tests if you have time. Right now, the project isn't hooked up to TravisCI so we don't have the benefit of the existing tests running automatically, so it's not a dealbreaker, but it will be nice to have for when we do.

**Comment by wintondeshong** [comment]
@brandongregoryscott appears the cli-dotnet-test is failing and the suite itself is hanging. We might need to configure a jest timeout too so if any test goes too long, jest just fails it. Once you resolve these issues in a new branch I'll publish a new version.

**Comment by wintondeshong** [comment]
Released in version 0.6.0
