### ISSUE TITLE
v1.0.0 Release

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.Cli#72]
Wanted to raise an issue so we can document discussion around revving the project to a 1.0.0 version, since it has matured quite a bit, and the testing suite has begun to take form.

Speaking of versioning, do we want to start tagging releases/versions in Github itself? That might make it easier to track down code changes between versions, and write up release notes.

**Comment by wintondeshong** [comment]
Yeah, I'm on board for the bump to v1.0.0 as well as leveraging tagging for releases accompanied by release notes. Not that it directly applies to this, but I am looking to further leverage releases/packages in github for our .net projects so we can use releases as a nuget source as well. All for it.

**Comment by wintondeshong** [comment]
Whatever our initial plan of attack is on tagging releases and change logs, we should have that be a part of the contributing/releases documentation in the primary AndcultureCode repo.

**Comment by brandongregoryscott** [comment]
@wintondeshong I drafted up a release - Can you take a look and let me know what you think? If it all looks good, we can commit the version change, publish it on npm, and tag the release here.

**Comment by brandongregoryscott** [comment]
Closing this. We've landed on a basic template that will be added to the [AndCultureCode/RELEASES.md](https://github.com/AndcultureCode/AndcultureCode/blob/master/RELEASES.md) file with AndCultureCode/AndCultureCode#5

v1.0.0 has been published to npm and tagged in Github. 🎉
