### ISSUE TITLE
Command to automatically configure workspace for AndcultureCode OSS contributions

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.Cli#73]
A really cool and helpful command would be an OSS contribution setup related one. Where it would both perform initial setup of a "workspace" for open source contributions as well as potentially sync an existing one with any "new" repos. Of course there will likely need to be discussion about what all is entailed in this setup. My initial thoughts for features are...

- [x] Project look up: Check github AndcultureCode organization for existing AndcultureCode repos following our established naming pattern `AndcultureCode.{language/technology}.{projectName}`
- [x] Clone Project setup: Clone 'main' branch of repo `ie. AndcultureCode.CSharp.Core`
- [x] Fork Project setup: Fork repo and clone fork of 'main' branch of repo in parallel to core project `ie. MyAndcultureCode.CSharp.Core`
- [x] Sync of workspace: If a given 'clone' or 'fork' project exists (given established naming convention) ignore! This would allow simple setup of new projects ongoing
- [x] Documentation: Update AndcultureCode contributing.md with this command

**Comment by brandongregoryscott** [comment]
This is a great idea! Having been confused about setting up a fork and how to pull upstream changes into it myself, I think this would really help get new faces familiar with the OSS contributing flow.

As far as dissect-able chunks, I think this is going to require a module that wraps `git`, which could be leveraged for #37, too. 

Another feature, though not necessarily required to get the initial issue complete, could be an "add fork" feature which would clone another contributor's fork of a repository for testing out their changes. It could prefix or postfix the repo with their username for quick access at a glance, something like `brandongregoryscott-fork-AndcultureCode.Cli` or `AndcultureCode.Cli-fork-brandongregoryscott`

**Comment by wintondeshong** [comment]
This is definitely going to be a series of PRs around the separate pieces of functionality. 

I'm going to bite off the base functionality of the `git` commands. Others can definitely take on other parts.

- Listing `AndcultureCode/AndcultureCode.*` prefixed repos
- Listing `{current-github-username}/AndcultureCode.*` prefixed repos (will likely require a prompt)
- Forking a given repo on github
- Setting `upstream` of a given user's fork to primary `AndcultureCode` repo

**Comment by wintondeshong** [comment]
Have the initial implementation of items 'Clone Project setup' and 'Sync of workspace' in my branch https://github.com/AndcultureCode/AndcultureCode.Cli/pull/114

**Comment by wintondeshong** [comment]
While there are more features to come, the requirements for this issue are met. Closing.
